# Generated by Django 4.1.4 on 2023-01-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_coupon_order_refund_payment_order_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
